name: app_channel   
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  # 序列化json的
  json_annotation: ^4.5.0

  # dio自动生成
  retrofit: ^3.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nightmare.applib_util
        pluginClass: ApplibUtilPlugin
